version: '3.8'

services:
  camera:
    build: ./model
    ports:
      - "5780:5780"

  backend:
    build: ./model/backend
    ports:
      - "5779:5779"


  client:
    build: ./client
    ports:
      - "5777:5777"

  server:
    build: ./server
    ports:
      - "5778:5778"
    depends_on:
     db:
      condition:  service_started

  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ai_project
    ports:
     - "3306:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db    # แก้ให้ตรงกับชื่อบริการของ MySQL
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
     - "8080:80"
    depends_on:
     - db
volumes:
  mysql_data_test: # กำหนดชื่อ volume ที่ต้องการจะสร้าง
    driver: local